id: I733A3394
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T17:56:57+00:00'
last_modified: '2022-06-08T17:22:47.915849+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22125
  title: ཧོར་ཆོས་རྗེ་སྐུ་འཕྲེང་གོང་མ་རྣམས་ཀྱི་རྣམ་ཐར་མདོར་བསྡུས་འཛམ་བུའི་གསེར་གྱི་སྙེ་མ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A047:
      image_group_id: I3508
      title: ''
      total_pages: 92
      order: 1
      base_file: A047.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
