id: I733A3394
legacy_id: P010767
ocr_import_info:
  bdrc_scan_id: W22125
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T17:56:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-01T20:44:13.846795+00:00'
last_modified: 2022-09-02 04:44:19.186777
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W22125
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW22125
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཧོར་ཆོས་རྗེ་སྐུ་འཕྲེང་གོང་མ་རྣམས་ཀྱི་རྣམ་ཐར་མདོར་བསྡུས་འཛམ་བུའི་གསེར་གྱི་སྙེ་མ།
  author: ཧོར་ཆོས་རྗེ ༠༣་དབྱངས་ཅན་སྙེམས་པའི་ལང་ཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.7609162072509408
  ocr_word_median_confidence_index: 0.8600000143051147
quality: null
bases:
  I3508:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3508
      total_pages: 92
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3508.txt
    statistics:
      ocr_word_median_confidence_index: 0.8600000143051147
      ocr_word_mean_confidence_index: 0.7609162072509408
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
